# Tensorflow2.0 小练习

In [1]:
import os
os.environ['TF_XLA_FLAGS'] = '--tf_xla_enable_xla_devices=false'
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import tensorflow as tf
import numpy as np

I0000 00:00:1774158100.890140 2392657 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1774158101.895572 2392657 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.


## 实现softmax函数

In [2]:
def softmax(x):
    x_tensor = tf.convert_to_tensor(x)
    
    x_max = tf.reduce_max(x_tensor, axis=-1, keepdims=True)
    exp_x = tf.exp(x_tensor - x_max)
    prob_x = exp_x / tf.reduce_sum(exp_x, axis=-1, keepdims=True)
    return prob_x

test_data = np.random.normal(size=[10, 5])
(softmax(test_data).numpy() - tf.nn.softmax(test_data, axis=-1).numpy())**2 <0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现sigmoid函数

In [3]:
def sigmoid(x):
    x_tensor = tf.convert_to_tensor(x)
    
    prob_x = 1.0 / (1.0 + tf.exp(-x_tensor))
    return prob_x

test_data = np.random.normal(size=[10, 5])
(sigmoid(test_data).numpy() - tf.nn.sigmoid(test_data).numpy())**2 < 0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现 softmax 交叉熵loss函数

In [4]:
def softmax_ce(x, label):
    x_tensor = tf.convert_to_tensor(x)
    label_tensor = tf.cast(label, dtype=x_tensor.dtype)
    
    epsilon = tf.cast(1e-7, dtype=x_tensor.dtype)
    
    ce_per_sample = -tf.reduce_sum(label_tensor * tf.math.log(x_tensor + epsilon), axis=-1)
    loss = tf.reduce_mean(ce_per_sample)
    return loss

test_data = np.random.normal(size=[10, 5])
prob = tf.nn.softmax(test_data)
label = np.zeros_like(test_data)
label[np.arange(10), np.random.randint(0, 5, size=10)]=1.

((tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(label, test_data))
  - softmax_ce(prob, label))**2 < 0.0001).numpy()

np.True_

## 实现 sigmoid 交叉熵loss函数

In [5]:
def sigmoid_ce(x, label):
    x_tensor = tf.convert_to_tensor(x)
    label_tensor = tf.cast(label, dtype=x_tensor.dtype)
    
    epsilon = tf.cast(1e-7, dtype=x_tensor.dtype)
    
    ce_per_sample = -(label_tensor * tf.math.log(x_tensor + epsilon) + 
                      (1.0 - label_tensor) * tf.math.log(1.0 - x_tensor + epsilon))
    loss = tf.reduce_mean(ce_per_sample)
    return loss

test_data = np.random.normal(size=[10])
prob = tf.nn.sigmoid(test_data)
label = np.random.randint(0, 2, 10).astype(test_data.dtype)
print (label)

((tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(label, test_data))- sigmoid_ce(prob, label))**2 < 0.0001).numpy()


[0. 1. 1. 0. 1. 1. 1. 0. 1. 0.]


np.True_